### ISSUE TITLE
Should not remove pathname from the query string

### ISSUE THREAD

**Issue by caasi** [c9s/qama#10]
![2016-07-13 17 21 25](https://cloud.githubusercontent.com/assets/1164470/16798381/5d5a75d8-491e-11e6-86f4-642cde4dc505.png)

應該是 `/qama/?answers=是` 才對，我寫爛了 0rz

**Comment by c9s** [comment]
沒關係, 看 field name 能不能用 init state index ? 這樣我們可以載入多組
